(module info (lib "infotab.ss" "setup")
  (define name "version-case")
  (define blurb '("version-case: conditional code based on mzscheme version"))
  (define categories '(misc))
  (define doc.txt "doc.txt")
  (define primary-file "version-case.ss")
  (define release-notes '("Added primitives version>=, version=, version>, and version>."))
  (define version "1.3"))